<?php $this->layout('layout::default', ['title' => 'ebest.pro']) ?>



<div class="row">
    <div class="col-md-12   ">
    <div class="card bg-primary shadow-soft text-center border-light">
            <div class="card-header">
                <span class="card-text small"><span class="far fa-calendar-alt mr-2"></span>15 mars 2024</span>
            </div>
            <div class="card-body">
                <h3 class="h5 card-title">Bienvenue sur EBEST.PRO</h3>
                <p class="card-text"></p>
                <a href="#" class="btn btn-primary btn-sm">+ d'infos</a>
            </div>
            <div class="card-footer">
                
            </div>
        </div>
    </div>



</div>
